spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  type-aliases-package: com.sinn.pojo #设置别名
  mapper-locations: classpath:mapper/*.xml   #ָ指定myBatis的核心配置文件与Mapper映射文件

logging:  #日志级别
  level:
    root: warn
    com.sinn: info
  #生产环境
  file:
    name: log/blog-pro.log